Vue/angular: fix loading panel for analytics page
DevExpress/devextreme-ui-template-gallery pull request #179
Opened 2022-11-22 12:58 UTC by Krijovnick

2022-11-24 06:28 UTC, dxvladislavvolkov submitted a review, later dismissed

2022-11-24 06:43 UTC, MikeVitik requested changes

2022-11-24 06:43 UTC, MikeVitik commented on packages/angular/src/app/pages/analytics-sales-report/analytics-sales-report.component.ts
> +        tasks.push(loader);
Remove subscribe and use async pipe

2022-11-24 06:43 UTC, MikeVitik commented on packages/vue/src/pages/analytics/analytics-sales-report/analytics-sales-report.vue
> +      .then((result: Sales) => { data[0].value = result; }),
use sales instead of data[0]

remove unused data after that

2022-11-25 06:28 UTC, MikeVitik approved these changes

2022-11-25 06:32 UTC, merged