Add handling for onSave of new task and new contact
DevExpress/devextreme-ui-template-gallery pull request #333
Opened 2023-10-24 16:24 UTC by GoodDayForSurf

2023-10-31 11:06 UTC, VasilyStrelyaev requested changes
Overall, judging by the React code and behavior, it's unclear to me what we are trying to achieve here. Maybe we need to write our intentions more clearly in the task description?

2023-10-31 11:06 UTC, VasilyStrelyaev commented on packages/react/src/components/library/contact-new-form/ContactNewForm.tsx
> +    setNewContactData({ ...initData });
Similarly to my comment in TaskFormDetails, this seems strange

2023-10-31 13:46 UTC, VasilyStrelyaev approved these changes

2023-11-01 08:27 UTC, ivanblinov2k17 approved these changes

2023-11-01 10:28 UTC, merged