Angular. Add Validators on Contact Form
DevExpress/devextreme-ui-template-gallery pull request #80
Opened 2022-09-26 21:10 UTC by GoodDayForSurf

2022-09-27 05:45 UTC, dxvladislavvolkov requested changes

2022-09-27 05:45 UTC, dxvladislavvolkov commented on packages/angular/src/app/pages/crm-contact-details/contact-form/contact-form.component.html
> +                     [visible]="!isEditing"
Fix indentation

2022-09-27 05:45 UTC, dxvladislavvolkov commented on packages/angular/src/app/pages/crm-contact-details/contact-form/contact-form.component.ts
> +  DxButtonModule, DxFormComponent,
Move to new line

2022-09-27 05:45 UTC, dxvladislavvolkov commented on packages/angular/src/app/pages/crm-contact-details/contact-form/contact-form.component.ts
> +  checkValidation = (e?) => {
Remove the argument

2022-09-27 05:45 UTC, dxvladislavvolkov commented on packages/angular/src/app/shared/components/form-item-plain/form-item-plain.component.ts
> +                               [type]="rule.type"
Fix indentation

2022-09-27 08:48 UTC, MikeVitik commented on packages/angular/src/app/pages/crm-contact-details/contact-form/contact-form.component.ts
> +  zipCodeValidator = { type: 'pattern', pattern: /\d{5}/, message: '5 digits' };
Please check the message to our help writers

2022-09-29 11:25 UTC, MikeVitik requested changes

2022-09-29 11:54 UTC, MikeVitik commented on packages/angular/src/app/pages/crm-contact-details/contact-form/contact-form.component.html
> +          ></edit-view-item>
Remove message

2022-09-29 14:18 UTC, Shuvaevmedia reviewed
Try placing the icon inside the field.

<dx-text-box
        value="password"
        placeholder="password"
        stylingMode="filled"
        [(mode)]="passwordMode"
      >
        <dxi-button
          name="today"
          location="before"
          [options]="passwordButton"
        ></dxi-button>
        
        https://js.devexpress.com/Demos/WidgetsGallery/Demo/Common/CustomTextEditorButtons/Angular/Light/

2022-09-29 14:19 UTC, Shuvaevmedia approved these changes

2022-09-29 14:24 UTC, MikeVitik approved these changes

2022-09-29 15:19 UTC, dxvladislavvolkov approved these changes

2022-09-29 15:45 UTC, merged