Master remake form field
DevExpress/devextreme-ui-template-gallery pull request #99
Opened 2022-10-12 18:36 UTC by GoodDayForSurf

2022-10-18 07:34 UTC, dxvladislavvolkov commented on packages/angular/src/app/pages/planning-task-details/task-form/task-form.component.ts
> +  DxToolbarModule, DxValidatorModule,
Move to a new line

2022-10-18 07:36 UTC, dxvladislavvolkov commented on packages/angular/src/styles.scss
> +      .form-editor-input {
Could we move editor styles to form-editor.component?

2022-10-18 07:37 UTC, dxvladislavvolkov reviewed
Some comments

2022-10-18 08:31 UTC, MikeVitik requested changes

2022-10-18 08:31 UTC, MikeVitik commented on packages/angular/src/styles.scss
> +  &.view-mode {
Move this piece of styles to the form-editor component

2022-10-18 16:11 UTC, dxvladislavvolkov approved these changes

2022-10-19 07:23 UTC, MikeVitik submitted a review, later dismissed

2022-10-19 07:31 UTC, dxvladislavvolkov submitted a review, later dismissed

2022-10-19 12:20 UTC, groshenkovamarina commented on packages/angular/src/app/shared/components/form-datebox/form-datebox.component.ts
> +  DxDropDownButtonComponent, DxDateBoxModule,
Move to a new line too

2022-10-19 19:27 UTC, dxvladislavvolkov approved these changes

2022-10-19 19:28 UTC, merged